### ISSUE TITLE
Rename to something less generic

### ISSUE THREAD

**Issue by mih** [adswa/multimatch_gaze#13]
"multimatch" could mean almost anything. It would help discoverabilty and co-existance if the name would be more specific. What about:

`gazepath_multimatch`

the term "scan path" is also very generic, and might best be avoided. Another possibility would be

`remodnav_multimatch`

which would communicate that the output of the former can easily go into this algorithm. The downside is that it could suggest a dependency that isn't actually there.

In any case, it is worth keeping the "multimatch" term.

And then, of course, there is the somewhat lame: `pymultimatch`

**Comment by adswa** [comment]
Good thought, thx. We did a vote and settled for ``multimatch_gaze`` - still has multimatch as a prefix, and gaze as opposed to gazepath makes it as short as possible.
