### ISSUE TITLE
Long run time for docomparison() with ~100 fixation points

### ISSUE THREAD

**Issue by mflan48** [adswa/multimatch_gaze#28]
I am attempting to use the docomparison() method in a python script I wrote and each scanpath has ~100 fixation points. The algorithm took more than 40 min to run and I am wondering what the (rough) complexity of the docomparison() method?  The python script example provided on the website ran almost instantly for me and those scanpaths had ~30 points.

**Comment by adswa** [comment]
Hi @mflan48, do you mind sharing the script and an example scanpath, so that I could look into that? 40min for a single scanpath comparison sounds surprisingly long. I've been using the algorithm on ~15min samples, and computation time wasn't more than a couple of minutes, so I'm wondering what's going on.

**Comment by mflan48** [comment]
Sure @adswa I'd be happy to. Here is the main() function in the script:
`

    fix_vector1 = np.recfromcsv('1_filtered.tsv', delimiter='\t', dtype={'names': ('start_x', 'start_y', 'duration'), 'formats': ('f8', 'f8', 'f8')})
    fix_vector2 = np.recfromcsv('2_filtered.tsv', delimiter='\t', dtype={'names': ('start_x', 'start_y', 'duration'), 'formats': ('f8', 'f8', 'f8')})

    results = mGaze.docomparison(fix_vector1,fix_vector2,screensize = [1300,731])
    print(results)
  `


And attached below are the two files that contain the scanpaths. Note: they were originally in .tsv format but have been copied and pasted into a .txt document in order to upload them to this message.
[1_filtered.txt](https://github.com/adswa/multimatch_gaze/files/3241544/1_filtered.txt)
[2_filtered.txt](https://github.com/adswa/multimatch_gaze/files/3241545/2_filtered.txt)

**Comment by adswa** [comment]
Hey @mflan48, thanks for the script & data!
I can confirm your observation, and must also admit that the longest scanpaths I've been testing with were at maximum half the size of your fixation vectors.

The bottleneck that leads to the long computation time is a dijkstra algorithm within ``docomparison`` ([here's the function](https://github.com/adswa/multimatch_gaze/blob/6f39b60ddc9a526b4b1728de360beb44a854c659/multimatch_gaze/multimatch_gaze.py#L459)). I believe my implementation of the algorithm is naive, in that it is not tuned for highest computational efficiency -- so there is room for improvement. For the next couple of weeks I won't have time to get into this (PRs are always welcome, though! :smile:). So for the problem at hand, I'm afraid I can't help you immediately.
If it is feasible to do so given your research question, you could split a fixation vector of yours into two.

**Comment by mflan48** [comment]
Hi @adswa , I have submitted a pull request for this issue. Please let me know if you have any questions.

**Comment by AlexMili** [comment]
Hello @adswa and @mflan48,

First of all thank you @adswa for your great work and thank you @mflan48 for your optimization. I am struggling with the same bottle neck with Dijkstra algorithm and @mflan48's work saved me a lot of time.
I would say that your code can again be optimized by replacing the line:
```python
arrayWeightedGraph = [[0 for x in range(numVert)] for y in range(numVert)]
```

by a numpy version of it:
```python
arrayWeightedGraph = np.zeros((numVert, numVert))
```
With this change, i got from 5.32s comparing 100 identical fixations to 0.71s !
But again Dijkstra algorithm remains the bottle neck. I found some [implementations with heapq](https://gist.github.com/kachayev/5990802). But I don't know what it worth and how it is possible to adapt it to our use case.

And just saying but @mflan48, in your PR, `scipy` requirement is missing from `requirements.txt` which make the tests fails ;)

**Comment by mflan48** [comment]
Hi @AlexMili,

I completely forgot about adding `scipy` to the `requirements.txt` file. I have updated the pull request to reflect this and I have also updated the `install_requires` attribute in the `setup.py` file as well.

Also, thank you for pointing out the optimization in the initialization of the `arrayWeightedGraph` variable. At first, I had changed it to `arrayWeightedGraph= np.zeros((numVert,numVert))` like you said. However, if `numVert` is large, the program would run out of memory and terminate (the fixation vectors I am dealing with have ~400-600 points, leading to a large `numVect` value).

To fix this, rather than creating a huge numpy array and then filling it in, the row, column, and weight values are stored in individual numpy arrays and then a csr_matrix is created from them. This saves a significant amount of memory and still runs at a reasonable time. I have updated the pull request to reflect this as well.

    #collect the row,col, and weight info from the weightedGraph 2d 
    rows = np.zeros(1)
    cols = np.zeros(1)
    data = np.zeros(1)

    #Convert the weightedGraph into a 2d matrix for scipy dijkstra
    for srcNode,dictEdges in weightedGraph.items():
        for destNode,weight in dictEdges.items():
            rows = np.append(rows,[srcNode])
            cols = np.append(cols,[destNode])
            data = np.append(data,[weight])

    #Create a scipy csr matrix from the rows,cols and append. This saves on memory.
    arrayWeightedGraph = (sp.coo_matrix((data,(rows,cols)),shape=(numVert,numVert))).tocsr()

**Comment by adswa** [comment]
Hey @mflan48, sorry it took me so long to get back to this, and thanks a lot! Much appreciated!
