### ISSUE TITLE
Input data type

### ISSUE THREAD

**Issue by LGurtner** [adswa/multimatch_gaze#41]
Hello, 
 first of all, thank you for implementing an open source version of the MultiMatch toolbox! 
I am trying to run your [demo, bottom of the page](https://multimatch.readthedocs.io/en/latest/api.html) but I keep getting the error `Conversion from numpy array type 20 is not supported`. I don't mind as much because I would rather like to provide the data within a script without saving the data as a tsv. However, I also run into these errors when I try other formats. The situation is also complicated by me working in R and calling Python via the `reticulate` package. But I would already be happy if you could tell me how exactly to specify an np.array (or np.recarray?) that `doComparison()` will accept (usually, it is `gen_scanpath_structure()` that is not happy). 
Thank you for your help!
(another thing: [here](https://multimatch.readthedocs.io/en/latest/reimplementation.html#getting-started) the module is called multimatch-gaze, but [here](https://pypi.org/project/multimatch/), the name is just multimatch. They are the same though, aren't they? They both point to the same GitHub page...)

Lilla

**Comment by adswa** [comment]
Hi @LGurtner,

could you provide me with maybe (a snippet from) your R script? I'm not used to working in R with Python, so I'm quite unfamiliar with this problem, but I have R installed and could try it out myself for more insights.

Re the name question: with the version-bump from v.0.1.0 to v.0.1.1 we introduced a module name change, because ``multimatch-gaze`` is easier to associate with scanpath comparison. Please make sure to use ``pip install multimatch-gaze`` as it is more up to date, and uninstall multimatch (``pip uninstall multimatch``). I might need to remove this package from Pypi, thanks for the pointer!

**Comment by LGurtner** [comment]
Hi @adswa, 
the script is really just in the trial-phase but here is some code that I use: 
`library(reticulate)
use_python("/usr/local/bin/python3", require = TRUE)
m <- import("multimatch-gaze")
np <- import("numpy")
fix_vector1 = np$recfromcsv('MYPATH/MMtrial1.tsv', delimiter='\t', dtype = dict(names = tuple("start_x", "start_y", "duration"), formats = tuple("f8", "f8", "f8")))`
If you want to try it in R, you're welcome to, but for me it would already be enough if you could tell me how you would create the input data in python. In R, I would for example have 
`Data1 <- list(start_x = c(495,946, 299, 846), 
               start_y = c(958,374,284,285), 
               duration = c(394, 923, 1192, 934))`
How would you write this to be accepted as a fixation vector for doComparison()?

**Comment by adswa** [comment]
Hey @LGurtner, thanks for the snippets. I'm a novice with this library, but could you quickly check whether a slightly changed module import
```
np <- import("numpy", convert=FALSE)
```
fixes your problem?

**Comment by adswa** [comment]
The changed import fixes the issue for me. Here is what I run:

```
library(reticulate)
> m <- import("multimatch_gaze")
> np <- import("numpy", convert=FALSE)
> fix_vector1 = np$recfromcsv('/home/adina/repos/multimatch/data/fixvectors/segment_0_sub-01.tsv', delimiter='\t', dtype = dict(names = tuple("start_x", "start_y", "duration"), formats = tuple("f8", "f8", "f8")))
> fix_vector2 = np$recfromcsv('/home/adina/repos/multimatch/data/fixvectors/segment_0_sub-19.tsv', delimiter='\t', dtype = dict(names = tuple("start_x", "start_y", "duration"), formats = tuple("f8", "f8", "f8")))
> m$docomparison(fix_vector1, fix_vector2, screensize=list(1280, 720))
[[1]]
[1] 0.9906726

[[2]]
[1] 0.6283904

[[3]]
[1] 0.9915381

[[4]]
[1] 0.8977883

[[5]]
[1] 0.3179704
```

The output format isn't as pretty as in Python, but the results in this toy example are correct. Please note though that I don't have any experience working with Python modules in R, and I'd recommend you to ask someone with more experience whether there are any caveats. As an alternative workaround, you could also always run the multimatch-gaze computations with a Python script, save the results, and load the results into your R script.

**Comment by LGurtner** [comment]
Dear Adina, 
thank you, that works for me too now! I was running a Python script aside until now, but now I need to make a lot of scan path comparisons and I don't want to be doing it "by hand". 
Well, thank you anyhow, also again for implementing an open source multimatch!
Best
Lilla

**Comment by adswa** [comment]
Wonderful, I'm glad it works! All the best :)
