### ISSUE TITLE
In some cases the loop in the "simplify_scanpath" function does not terminate 

### ISSUE THREAD

**Issue by LFaggi** [adswa/multimatch_gaze#46]
Hi, as the title says, there may be a little bug in the simplify_scanpath function. I experienced this few times while testing your package with some of my own scanpaths. 

The problem is that the loop inside that function does not terminate in some cases. While looptime increases each step, len(path["fix"]["dur"]) may diminishes but there could be cases in which  looptime== len(path["fix"]["dur"]) never occurs indeed. 
Example: 
looptime - len(path["fix"]["dur"])
1 - 10
2 - 9
3 - 8
4 - 7
5 - 6
6 - 5
7 - 4
8 - 4 
9 - 4 
...                  ...
and so on and so forth.

Something like this:
```
prev_length = len(path["fix"]["dur"])
    while True:
        path = simdir(path, TDir, TDur)
        path = simlen(path, TAmp, TDur)
        length = len(path["fix"]["dur"])
        if length == prev_length:
            return path
        else:
            prev_length = length
```

may resolve the issue?

Best, 

Lapo

**Comment by adswa** [comment]
Thank you for catching this, @LFaggi, and also thanks a lot for the fix!
I have PR'ed your change in #47. Would you mind sharing a short scanpath file of yours that triggers the bug, so that I can add a unit test?

**Comment by LFaggi** [comment]
Dear @adswa, 

you are welcome! Sorry for my late response but I have been busy these days.
With the attached scanpath you should  be able to reproduce the issue. 

[Scanpath_infinite_loop.txt](https://github.com/adswa/multimatch_gaze/files/5702491/Scanpath_infinite_loop.txt)

The third and fourth columns stand for the start/end time of the corresponding fixation. 
You have to read the scanpath through the following function:

```
def read_scanpath(scanpath_path, delimeter = ' '):
    '''It returns a numpy array with shape (number_of_frames, 3) or (number_of_fixations,4) depending on the input.'''
    with open(scanpath_path, 'r') as f:
        stripped = (row.strip() for row in f)
        f_reader = csv.reader(stripped, delimiter=delimeter)
        simulated_scanpath = []
        for line in f_reader:
            simulated_scanpath.append(np.array(line).astype(float))

    return np.array(simulated_scanpath)
```


and then convert it in a form suitable for your package through:

```
def convert_to_recarray(input_path):
    """Convert the input scanpath to a format suitable for the multimatch package,
     that is a numpy record array in which each entry is expressed as (x,y,duration).
     """
    fix = read_scanpath(input_path)
    fix_new = np.zeros((fix.shape[0], 3))

    for i in range(fix.shape[0]):
        fix_new[i, 0] = fix[i, 0]
        fix_new[i, 1] = fix[i, 1]
        fix_new[i, 2] = fix[i, 3] - fix[i, 2]

    return np.core.records.fromarrays(fix_new.transpose(), dtype={'names': ('start_x', 'start_y', 'duration'),
    'formats': ('f8', 'f8', 'f8')})
```

Best,

Lapo

**Comment by adswa** [comment]
Thank you so much @LFaggi! One more (hopefully last) question though: Could you share with which simplification thresholds you ran into this on this file? I'm having a hard time reproducing it, but I assume it happens with a specific threshold configuration :)

**Comment by LFaggi** [comment]
I used the default values found in the [documentation ](https://multimatch.readthedocs.io/en/latest/api.html), in particular: 

TDir=30.0, TDur=0.1, TAmp=100.1 

Please, let me know if with these thresholds you can reproduce the issue!

**Comment by adswa** [comment]
Yes! Thanks, I can trigger it now! :)
